sudo: required

services:
  - docker

before_install:
- docker build --build-arg=maxmind_license_key="$maxmind_license_key" --tag=ikelewis/my-geo-ip .

script:
- echo "Build Passing"

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push ikelewis/my-geo-ip;
  fi